<a href="https://colab.research.google.com/github/Meett27/DataAnalyticsWithPython/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [4]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:

fives_array = np.full(10, 5)
fives_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [8]:
array_10_to_50 = np.arange(10, 51)
array_10_to_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
even_array = np.arange(10, 51, 2)
even_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [15]:
random_number = np.random.rand()
random_number

0.3730641137396974

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [16]:
random_numbers = np.random.randn(25)
random_numbers

array([ 1.18097046,  1.53153378, -0.30671511, -1.00404991, -0.59747267,
        0.65620176,  0.30915894,  1.70287668,  1.18255327,  0.69607491,
       -0.32463757,  2.60784533, -1.38789423, -1.89417796,  1.13281576,
        0.54568174, -0.80201928, -0.39265711,  0.86504594,  0.86600662,
        0.60299539, -0.2752917 ,  1.23354929,  0.0380177 ,  1.19541269])

#### Create the following matrix:

In [17]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
matrixa = np.array([[12, 13, 14, 15],
                   [17, 18, 19, 20],
                   [22, 23, 24, 25]])
matrixa

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
value = matrixa[1, 3]
print(value)

20


20

In [27]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
result = np.arange(21, 26)
result

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
matrixb = np.array([[16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
matrixb

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])